### ISSUE TITLE
Unable to use hivesigner for waivio

### ISSUE THREAD

**Issue by igster101** [ledgerconnect/hivesigner#20]
### Steps to reproduce the behavior Attempt to sign in. Spins and  spins
Attempt to import my account again(just because)  enter info, spins and spins

**Comment by feruzm** [comment]
@igster101 Thanks, could you provide link to the app if available to test out the integration?

Can you check if there are console errors during those spins? 
> Browser window and select More Tools > Developer Tools. You can also use the shortcut Option + ⌘ + J (on macOS), or Shift + CTRL + J (on Windows/Linux).

**Comment by igster101** [comment]
waivio.com
Error with Feature-Policy header: Unrecognized feature: 'speaker'.
5chrome-extension://invalid/:1 Failed to load resource: net::ERR_FAILED
login:1 Denying load of chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/honey_pay/index.html. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
chrome-extension://invalid/:1 Failed to load resource: net::ERR_FAILED

**Comment by igster101** [comment]
I turned off all extensions and get
Error with Feature-Policy header: Unrecognized feature: 'speaker'.

**Comment by feruzm** [comment]
Interesting, 
https://www.waivio.com/callback? seem to return 502 error, could you check if your callback is accessible and setup properly?

**Comment by igster101** [comment]
I'm not sure what that is

**Comment by feruzm** [comment]
It is waivio.com callback which handles getting user back to waivio.com after successful login on hivesigner. If you are/know developer, perhaps can take a look login callback functionality maybe some bug introduced on that page. I just tried login and after login got 502 error on callback, hivesigner part worked but website part didn't.

**Comment by igster101** [comment]
Thank you for all your help.
