### ISSUE TITLE
Settings page requires a redesign

### ISSUE THREAD

**Issue by bala-techguy** [ledgerconnect/hivesigner#3]
It took me lots of time to identify where I can make changes for my account. 

![image](https://user-images.githubusercontent.com/23168216/78326708-aa3fad00-7598-11ea-8565-9d4558f7a033.png)

This can be made a little more user friendly. I guess the below part can be there directly on the Setting page instead of navigating inside accounts. 

![image](https://user-images.githubusercontent.com/23168216/78326854-fee32800-7598-11ea-8c97-ea80b161d6f9.png)

**Comment by feruzm** [comment]
Settings available directly from Home page though, have you seen it?! Maybe structure or navigation pages could be changed a bit so there is little bit more highlight on them

![image](https://user-images.githubusercontent.com/3015990/78352970-f9460c00-75b1-11ea-857d-a8be52b41fc5.png)

**Comment by bala-techguy** [comment]
Yes, Settings page is easily accessible. But inside that, it took a while for me to understand that I have to click on "Accounts" to make changes to the settings.

**Comment by feruzm** [comment]
Accounts added!
