### ISSUE TITLE
Missing Active Authority ERROR auth 

### ISSUE THREAD

**Issue by nakasofi** [ledgerconnect/hivesigner#32]
### Steps to reproduce the behavior

I cannot revoke or grant authority, this "Missing Active Authority auth={"weight_threshold":1,"account_auths":[]," I am using the right key, so I do not what is the problem, I can’t even login “You need to import your account using your password or at least active key to do this request. Click "Import account" button to proceed”  but I used my password o my active key and it doesn’t work I have to import my account everytime to enter but it doesn’t matter because I can’t grand or revoke authority, I can’t do anything.

**Comment by feruzm** [comment]
@nakasofi I just pushed few improvements, can you test again, please? Thanks!

**Comment by nakasofi** [comment]
Thank you a lot! :) I'm very grateful.
