### ISSUE TITLE
Unable to use Hivesigner extension

### ISSUE THREAD

**Issue by bala-techguy** [ledgerconnect/hivesigner#4]
I installed HiveSigner extension on my Brave browser. I tried to make a comment using PeakD and got the below error message from the extension. 

![image](https://user-images.githubusercontent.com/23168216/78328060-d7418f00-759b-11ea-9a1f-c4e8f0899a73.png)

I even tried logging out and logging in again but still end up with the same error message. I then had to remove the extension from the browser to continue my posting activities.

**Comment by feruzm** [comment]
Thank you, we are looking into this and submit update asap with mentioned changes from our latest post!

**Comment by feruzm** [comment]
Update: 
1. Turns out peakd was using older SDK, notified them they are working on fix.
2. We have submitted update to Chrome store as well, it should be available in couple days with all new changes. Please recheck then and reopen if issue persist. Thank you!
