### ISSUE TITLE
Discord Link Expired 

### ISSUE THREAD

**Issue by bartosz546** [ledgerconnect/hivesigner#7]
### Expected behavior
Join Discrod Server

### Actual behavior
In Contact Us tab, if I click "Join us on Discord", I get message, that invitation expired. 

### Steps to reproduce the behavior
1. open https://hivesigner.com/
2. Go to "Contact us Tab"
3. Click "Join us on Discord" link

**Comment by feruzm** [comment]
Please try this: https://discord.gg/pNJn7wh
I will update links in other places as well. Thanks!

**Comment by feruzm** [comment]
Done
