### ISSUE TITLE
Hivesigner Chrome extension says "Invalid username or password"

### ISSUE THREAD

**Issue by shenzhenadam** [ledgerconnect/hivesigner#9]
Hivesigner Chrome extension says "Invalid username or password 
... Invalid username or password. You need to use master, active, posting or memo key to log in"

I tried master, active, posting or memo keys to sign in, but same result ....

Please advise what to do

**Comment by feruzm** [comment]
@shenzhenadam Are you using latest version? Could you show full error message or check Developers console to see if you get some extra information?

**Comment by feruzm** [comment]
@shenzhenadam any updates on this issue? We have pushed 0.2.0 version of Hivesigner extension, please try that and let us know if you still experience the issue.

**Comment by feruzm** [comment]
closing this, as we have deprecated Hivesigner extension!
